version: '3.8'

services:
  master_postgres:
    container_name: master_postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zenqara_db
    ports:
      - '5432:5432'
    networks:
      - backend_network

networks:
  backend_network:
    external: true
