version: '3.8'

services:
  master_postgres:
    container_name: master_postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zenqara_db
    ports:
      - '5432:5432'
    networks:
      - backend_network

  master_redis:
    container_name: master_redis
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
    networks:
      - backend_network

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    command: server --console-address :9001 /data
    networks:
      - backend_network

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 user password;
      /usr/bin/mc mb minio/corpbucket;
      /usr/bin/mc anonymous set public minio/corpbucket;
      exit 0;
      "
    networks:
      - backend_network

networks:
  backend_network:
    external: true
